@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

TaskManager *-right-> "1" UniqueTaskList
TaskManager *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueTaskList
UniqueTagList -[hidden]down- UniqueTaskList

UniqueTagList *-right-> "*" Tag
UniqueTaskList o-right-> Task

Task -up-> "*" Tag

Task *--> Title
Task *--> Description
Task *--> Priority
Task *--> DoneStatus
@enduml
