@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyTaskManager <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class TaskManager
Class ReadOnlyTaskManager
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Task {
Class "{abstract}\nTask" as Task
Class Description
Class DoneStatus
Class Title
Class Priority
Class UniqueTaskList
Class ToDo
Class Event
Class Deadline
Class TaskDate
Class TaskTime
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

TaskManager .up.|> ReadOnlyTaskManager

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" TaskManager
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

TaskManager *--> "1" UniqueTaskList
UniqueTaskList o--> "*" Task
Task *--> Title
Task *--> Priority
Task *--> DoneStatus
Task *--> Description
Task *--> "*" Tag

ToDo -left-|> Task
Deadline -left-|> Task
Event -left-|> Task

Deadline *-down-> TaskDate
Event *-down-> TaskDate
Event *-down-> TaskTime

Title -[hidden]right-> Priority
Priority -[hidden]right-> Description
Description -[hidden]right-> DoneStatus

ModelManager -->"1" Task : filtered list
@enduml
